"""The broad fund universe downloaded by scripts/fetch_data.py besides the core lists in that script: the
most-held US-listed ETFs across asset classes and about 150 popular mutual funds (Yahoo serves mutual funds
as a daily NAV with dividends, i.e. a total-return history, most from the 1980s or their launch).

These are refreshed in rotating batches (BROAD_PER_RUN in scripts/fetch_data.py): each run downloads the
files that are missing first, then the ones updated longest ago, so every run stays short and polite to
Yahoo. A symbol Yahoo doesn't know is retried once a month, not every run.

They are funds, never index members: backtester/data.py strips every symbol here from the Nasdaq-100
membership history. To add a symbol, append it to the right list (or put it in data/extra_tickers.txt).

Sources of the lists added on 2026-09-27 (each checked against the issuer's own fund list that day):
  Vanguard       every retail mutual fund share class (Investor / Admiral; no money market, 529, institutional or
                 variable-insurance classes) in Vanguard's fund catalog, investor.vanguard.com/investment-products/list/
                 funddetail/all
  Dimensional    every mutual fund on dimensional.com/us-en/funds (no target-date or single-state muni portfolios)
  Schwab         every mutual fund (no money market) on schwabassetmanagement.com/product-finder
  American Funds the Class A ticker of every fund on capitalgroup.com/individual/investments/mutual-funds (no money market)
  Dodge & Cox    Class I and X of every fund on dodgeandcox.com (fund list page)
  Fidelity, T. Rowe Price: well-known funds added by hand (those issuers' fund lists could not be read from here); a
                 symbol Yahoo doesn't know is simply skipped by the data job (broad_failed in data/universe.json).
Yahoo's mutual-fund histories start in January 1980 at the earliest (its chart API reports firstTradeDate
1980-01-02 even for VWELX, a 1929 fund), so nothing older is available from it; the SIM series cover earlier years.

LARGE_OTHER_STOCKS: the 300 largest US-listed stocks outside the S&P 500/400/600 (mostly ADRs and foreign
listings, plus large US companies not in the indexes), by market cap on stockanalysis.com's lists on 2026-09-27.
The S&P 500/400/600 members themselves are read from Wikipedia by the data job (data/index_constituents.json).
They are stocks: never funds, never Nasdaq-100 members (membership comes only from the Nasdaq-100 history).
"""
from __future__ import annotations

# ETFs by asset class (the core list in scripts/fetch_data.py already has many; duplicates are harmless)
BROAD_ETFS_BY_CLASS = {
    "US total market / large cap": """
VTI VOO SPY IVV ITOT SCHB SPTM IWV VV SCHX IWB SPLG VONE MGC VXF DIA RSP OEF XLG SCHK ESGU ESGV SUSA DSI""",
    "US large growth / value": """
VUG VTV IWF IWD SCHG SCHV SPYG SPYV IVW IVE VONG VONV MGK MGV IUSG IUSV VOOG VOOV RPG RPV IWY IWX""",
    "US mid cap": """
VO IJH MDY IWR SCHM SPMD VOE VOT IWS IWP IJK IJJ XMLV XMHQ""",
    "US small cap": """
VB IJR IWM SCHA SPSM VBR VBK IWN IWO IJS IJT SLYV SLYG VTWO VIOO VIOV CALF IWC""",
    "Avantis": """
AVUV AVDV AVEM AVLV AVUS AVDE AVIV AVES AVSC AVMV AVRE AVIG AVSD""",
    "Dimensional": """
DFAC DFAU DFUS DFAT DFSV DFLV DFAS DFAI DFIV DFIS DISV DFEM DFEV DFAX DFCF DFIP DFNM DFSD DFAR DFGR""",
    "factor / smart beta": """
MTUM QUAL USMV VLUE SIZE SPHQ SPLV SPHB VFMF VFQY VFVA VFMO VFMV COWZ MOAT FNDX FNDA FNDF PRF JQUA
IMTM IQLT IVLU EFAV EEMV ACWV""",
    "dividend / income": """
SCHD VIG VYM DVY HDV SDY NOBL DGRO FDVV SPYD DGRW VYMI VIGI IDV JEPI JEPQ DIVO QYLD XYLD RYLD""",
    "growth / thematic": """
QQQ QQQM ONEQ ARKK ARKG ARKW ARKQ ARKF TAN ICLN LIT URA BOTZ ROBO HACK CIBR SKYY CLOU FINX ESPO BLOK KWEB
PBW FAN FDN IGV SOXX SMH XSD""",
    "sector (SPDR / Vanguard / iShares)": """
XLK XLF XLE XLV XLY XLP XLI XLU XLB XLRE XLC VGT VFH VDE VHT VCR VDC VIS VPU VAW VOX
IYW IYF IYE IYH IYC IYK IYJ IDU IYM IYZ IYT IBB IHI IHF ITA ITB IAK IAT KRE KBE XBI XHB XRT XME XOP XES
XAR XPH XHE XTN XSW OIH PAVE JETS IGF GRID""",
    "international broad / regional": """
VEA VXUS VEU VWO IEFA IEMG EFA EEM SCHF SCHE SCHC SPDW SPEM IXUS ACWI ACWX VT URTH EFG EFV SCZ VSS VGK VPL
IEUR EZU FEZ HEDJ DXJ GWX IDEV IEV ILF AAXJ EPP EWX""",
    "country": """
EWJ EWG EWU EWZ FXI MCHI INDA EWC EWA EWY EWT EWH EWS EWM EWP EWI EWQ EWL EWN EWD EWK EWO ENZL EDEN EFNL
ENOR EIRL EWW ECH EPOL TUR EZA EIDO THD EPHE VNM KSA ARGT GXC ASHR INDY SMIN EPI EWZS""",
    "US Treasuries / aggregate": """
AGG BND IUSB SCHZ SPAB FBND TOTL BSV BIV BLV VGSH VGIT VGLT GOVT SHY IEI IEF TLH TLT EDV ZROZ SPTS SPTI
SPTL SCHO SCHR SCHQ ISTB VMBS MBB SPMB""",
    "corporate bonds": """
VCSH VCIT VCLT IGSB IGIB IGLB USIG LQD SPSB SPIB SPLB SCHI SCHJ""",
    "high yield / loans": """
HYG JNK SHYG SJNK USHY HYLB ANGL FALN BKLN SRLN""",
    "international / EM bonds": """
BNDX IAGG BWX IGOV EMB VWOB PCY EMLC LEMB""",
    "municipal bonds": """
MUB VTEB TFI SUB SHM HYD HYMB PZA""",
    "TIPS": """
TIP SCHP VTIP STIP SPIP LTPZ TIPX TDTT""",
    "cash / ultra-short": """
BIL SGOV SHV TFLO USFR FLOT MINT JPST NEAR ICSH GSY VRIG FLRN""",
    "real estate": """
VNQ VNQI RWO REET RWR SCHH IYR USRT ICF RWX REM MORT FREL""",
    "commodities / precious metals": """
DBC PDBC GSG DJP BCI COMT CMDY FTGC USCI DBA DBB DBE DBO DBP GLD IAU GLDM SGOL BAR AAAU SLV SIVR PPLT PALL
USO BNO UNG UGA CPER CORN WEAT SOYB GDX GDXJ SIL""",
    "alternatives / managed futures": """
TAIL CTA DBMF KMLM BTAL QAI MNA RPAR NTSX NTSI NTSE PFIX SVOL""",
    "currencies": """
UUP UDN USDU FXE FXY FXF FXB FXA FXC""",
    "crypto": """
IBIT FBTC BITB ARKB GBTC ETHA ETHE BITO""",
}

# leveraged and inverse ETFs used in Composer-style symphonies (ProShares, Direxion, MicroSectors, ...)
LEVERAGED_ETFS = """
TQQQ SQQQ QLD QID PSQ UPRO SPXU SSO SDS SH SPXL SPXS SPUU UDOW SDOW DDM DXD DOG UWM TWM RWM URTY SRTY TNA TZA
MVV MZZ UMDD SMDD MIDU SAA SDD ROM REW USD SSG UYG SKF RXL RXD UGE SZK UXI UYM SMN DIG DUG URE SRS UPW SDP
BIB BIS UBT TBT TBF TBX UST PST TTT TMF TMV TYD TYO UCO SCO BOIL KOLD UGL GLL AGQ ZSL YCS YCL EUO ULE
SOXL SOXS TECL TECS FAS FAZ ERX ERY LABU LABD DRN DRV CURE DPST NAIL RETL DFEN WEBL WEBS HIBL HIBS UTSL
PILL TPOR WANT DUSL BRZU KORU MEXX EURL CHAU CWEB YINN YANG EDC EDZ INDL JNUG JDST NUGT DUST GUSH DRIP
FNGU FNGD FNGO BNKU BNKD NRGU NRGD OILU OILD GDXU GDXD
BITX BITI BITU SBIT ETHU ETHT ETHD CONL NVDL NVDS NVDX NVDQ TSLL TSLQ TSLS MSTU MSTZ AAPU AMZU GGLL MSFU METU
UVXY SVXY VIXY VIXM UVIX SVIX TARK SARK
"""

# popular mutual funds (Yahoo symbols); daily NAV with dividends
MUTUAL_FUNDS_BY_FAMILY = {
    "Vanguard": """
VFINX VFIAX VTSMX VTSAX VTIAX VGTSX VBMFX VBTLX VWELX VWENX VWINX VWIAX VGSLX VGSIX VFSTX VFSUX VWEHX VWEAX
VIPSX VAIPX VFITX VSIGX VUSTX VLGSX VBIRX VBILX VBLTX VWESX VWETX VFICX VWITX VWIUX VWLTX VWLUX VWSTX
VMLTX VTEAX VTABX VTMGX VEIEX VEMAX VEURX VPACX VTRIX VINEX VIMSX VIMAX NAESX VSMAX VISVX VSIAX VISGX
VSGAX VIVAX VVIAX VIGRX VIGAX VEXMX VEXAX VHDYX VDIGX VDADX VPMCX VPCCX VPMAX VWUSX VWNDX VWNFX VGHCX
VGENX VGPMX VTWSX VBIAX VBINX VASGX VASIX VSCGX VSMGX VGSTX VQNPX VHGEX VTMSX VMVIX VMGIX VFTSX VSEQX""",
    "Fidelity": """
FXAIX FSKAX FTIHX FXNAX FCNTX FMAGX FDGRX FBGRX FLPSX FOCPX FSELX FSPTX FBIOX FDVLX FEQIX FEQTX FGRIX
FPURX FBALX FFIDX FDIVX FIEUX FOSFX FSMDX FSSNX FSMAX FZROX FZILX FNILX FUAMX FGOVX FTBFX FNMIX FAGIX SPHIX
FRESX FSUTX FSENX FSCHX FSDAX FSRBX FSHCX FSCPX FSAGX FSRRX FSICX FLTMX""",
    "Dimensional": """
DFSVX DFLVX DFUSX DFQTX DFEOX DFCEX DFEMX DFEVX DFIVX DISVX DFISX DFALX DFSCX DFSTX DFREX DFGBX DFIHX
DFIEX DFVEX DFFVX DFIGX DFGEX""",
    "Vanguard (all retail share classes)": """
VBIRX VSCSX VSGBX VSGDX VFSTX VFSUX VFISX VFIRX VSBSX VUBFX VUSFX VCORX VCOBX VCPIX VCPAX VFIIX VFIJX VWEHX VWEAX
VBILX VICSX VFICX VFIDX VFITX VFIUX VSIGX VMBSX VTEAX VBTLX VIPSX VAIPX VTAPX VEMBX VEGBX VGAVX VGCIX VGCAX VBLAX
VLTCX VWESX VWETX VUSTX VUSUX VLGSX VMSIX VMSAX VTABX VMLTX VMLUX VWSTX VWSUX VCAIX VCADX VWITX VWIUX VCITX VCLAX
VWAHX VWALX VWLTX VWLUX VMATX VNJTX VNJUX VNYTX VNYUX VOHIX VPAIX VPALX VBIAX VASIX VSCGX VSMGX VASGX VGSTX VTINX
VTWNX VTTVX VTHRX VTTHX VFORX VTIVX VFIFX VFFVX VTTSX VLXVX VSVNX VTMFX VWINX VWIAX VWELX VWENX VGWIX VGYAX VGWLX
VGWAX VFIAX VADGX VDEQX VDADX VDIGX VEIPX VEIRX VFTAX VQNPX VGIAX VHYAX VMNFX VIGAX VLCAX VTSAX VVIAX VPCCX VTCLX
VWUSX VWUAX VFMFX VWNDX VWNEX VWNFX VWNAX VHCOX VHCAX VEXPX VEXRX VEVFX VEXAX VMGRX VMGMX VIMAX VMVAX VSGAX VSMAX
VSIAX VPMCX VPMAX VASVX VSEQX VSTCX VTMSX VTCAX VCDAX VCSAX VENAX VGENX VGELX VFAIX VGHCX VGHAX VHCIX VINAX VITAX
VMIAX VGSLX VUIAX VAGVX VAIGX VBPIX VTMGX VMMSX VEMAX VEUSX VFWAX VFSAX VGPMX VEOIX VEOAX VHGEX VEIGX VESGX VGRLX
VMVFX VMNVX VWICX VZICX VIAAX VIDGX VINEX VWIGX VWILX VIHAX VTRIX VPADX VTIAX VTWAX VCMDX""",
    "Dimensional (all)": """
DAABX DAADX DADIX DCMSX DEMGX DEMSX DESIX DFAAX DFABX DFAIX DFALX DFAPX DFCEX DFCFX DFCSX DFELX DFEMX DFEOX DFEQX
DFESX DFETX DFEVX DFFGX DFFVX DFGBX DFGEX DFGFX DFIEX DFIGX DFIHX DFISX DFITX DFIVX DFJSX DFLVX DFMPX DFQTX DFREX
DFRSX DFSCX DFSHX DFSIX DFSMX DFSPX DFSTX DFSVX DFTEX DFTIX DFUEX DFUKX DFUSX DFUVX DFVEX DFVIX DFVQX DFWIX DFWVX
DFXIX DFYGX DGBEX DGCFX DGEIX DGLIX DGSFX DGSIX DGTSX DIHRX DILRX DIPSX DISMX DISVX DMREX DREIX DRXIX DSCGX DSCLX
DSFIX DSHGX DSSMX DTCPX DURPX DUSLX DUSQX DWFIX DWUSX""",
    "Schwab": """
LGILX SFENX SFILX SFLNX SFNNX SFREX SFSNX SICNX SNXFX SWAGX SWANX SWASX SWBGX SWCAX SWCGX SWDSX SWEGX SWHFX SWHGX
SWHYX SWISX SWLGX SWLSX SWLVX SWMCX SWMIX SWNTX SWOBX SWPPX SWRSX SWSBX SWSCX SWSSX SWTSX""",
    "American Funds (Class A)": """
EMEEX AEPGX ANEFX ANWPX AMCPX AGTHX SMCWX NEWFX AGVFX AIVBX CWGIX IGAAX AMRMX ANCFX AIVSX AWSHX DWGAX CAIBX AMECX
GBLAX ABALX AHITX AFCPX BFCAX EBNAX BFIAX MIAQX ANBAX ASBAX AIBAX AMUSX MFAAX ABNDX CWBFX AMHIX ASTEX NYAAX LTEBX
AFTEX TAFTX""",
    "Dodge & Cox": """
DODGX DOXGX DODWX DOXWX DODFX DOXFX DODEX DODBX DOXBX DODIX DOXIX DODLX DOXLX""",
    "Fidelity (index and major funds)": """
FSPSX FPADX FSRNX FIPDX FUMBX FNBGX FSGGX FLCOX FSPGX FNSOX FITLX FDSVX FFFFX FADMX FBNDX FDGFX FMCSX FSCRX
FLVCX FIGRX FEMKX FSPHX FSCSX FIDSX FDFAX FSRPX FSRFX FSMEX FPHAX FSDPX FNARX FCYIX FBMPX FBSOX""",
    "T. Rowe Price": """
PREIX POMIX PRFDX PRITX PRMTX PRSVX OTCFX RPMGX TRMCX PRCIX PRHYX PRULX PRGSX PRIDX PRGTX PRDMX PRESX PRJPX
PRASX PREMX PRNEX""",
    "PIMCO": """
PTTRX PTTAX PIMIX PFORX PFUIX PCRIX PCRAX PRRIX PHIYX PEBIX PAAIX PAUIX PSTKX PSLDX PEDIX PGOVX PTSHX PTLDX""",
    "American Funds": """
AGTHX AIVSX ANCFX AWSHX AMCPX CWGIX AEPGX NEWFX SMCWX ANWPX CAIBX AMECX ABALX ABNDX AHITX""",
    "other": """
PRPFX VPMCX DODGX DODFX DODIX DODBX FAIRX SEQUX OAKMX OAKIX PRWCX PRGFX TRBCX PRNHX PRHSX PRDGX PRBLX
POAGX POGRX TWCUX BRUFX MERFX QSPIX AQMIX QMNIX SGIIX SGENX LSBRX MWTRX MWTIX HAINX HACAX MALOX TEPLX
FKINX ULPIX UOPIX RYNVX""",
}

# stocks outside the Nasdaq-100 that symphonies use (kept apart from the funds)
EXTRA_STOCKS = "SQM"

# the 300 largest US-listed stocks outside the S&P 1500 on 2026-09-27 (see the module docstring), largest first
LARGE_OTHER_STOCKS = """
SPCX TSM SKHY ASML HSBC ARM RY NVS SHEL BABA MUFG AZN SAP TM BHP SAN TTE TD SHOP SCCO
NVO SMFG RIO BBVA BUD UBS SONY UL MFG PBR NET BMO BTI SNOW HDB BP BNS PDD SPOT ENB
CM ING EQNR IBN AEM GSK SNY CNQ ASX SOMN ITUB MELI LYG BN BCS E SU EPD RACE CP
NGG NTES NWG CNI MFC BAM B ET DB AMX NU NBIS WPM ALAB TRP SE MSTR UMC TAK ARGX
NTRA IMO NOK RELX VALE MPLX CVE LNG MT AU FNV CBRS DEO CRWV TEAM STM TEVA MDLN ABEV KB
CCEP SLF RKLB RVMD HEI IX TRI HMC WDS INFY CLS ONC HLN FER CRDO WCN CCJ VOD SHG FMX
VIK GFI JD CHT ESLT NTR RKT ALNY BBD EC UI RPRX RBLX MDB QSR TECK VG ZS ERIC ALC
PUK SUNB CQP BAP BIDU KGC NMR TS RYAAY FTS GFS SYM ZM TSEM PBA INSM CPNG TCOM BNTX LPLA
PHG AFRM CIB ASTS GH FWONK TW FCNCA KOF IHG AER CRCL RBRK PS RIVN IOT PAAS BCE BEP BEKE
RCI MGA FUTU ZTO EMA AGI EQX GIB TME YUMC TU HTHT HBM LI IAG EGO TFII DRS BEPC PSO
XPEV ENLT GLXY AG SIMO KYMR JAN ESTC LINE SNAP QGEN KT OSCR LLYVA CAI ELPC NIO SSL IBRX GGB
EDU RIOT AAOI TIMB YMM BVN PCVX ABVX BOKF CAE HESM WULF PRAX GTLB S STN HNGE CBC APLD GIL
LEVI SYRE VIST UGP SFD PCOR SBSW VFS IONS ZETA CIFR SSRM ASR BTG NTSK FIGR COMP SOBO OKLO PRMB
CIG-C AUGO AXS IMVT CAMT VIPS MBLY MAAS RYTM NICE GLBE BLTE DSGX TAP OR TAL ICL TFPM GGAL OMF
GDS PACS GRFS TBBB QBTS Z BLDR PL BZ OGC LB JOBY BILI INGM PAGP IFS NXE XE DPC LOAR
"""


def _split(s: str) -> list[str]:
    return list(dict.fromkeys(s.split()))


BROAD_ETFS = _split(" ".join(BROAD_ETFS_BY_CLASS.values()) + " " + LEVERAGED_ETFS)
MUTUAL_FUNDS = _split(" ".join(MUTUAL_FUNDS_BY_FAMILY.values()))
BROAD_STOCKS = _split(EXTRA_STOCKS)
OTHER_STOCKS = [t for t in _split(LARGE_OTHER_STOCKS) if t not in set(BROAD_ETFS) | set(MUTUAL_FUNDS)]
ALL_FUNDS = frozenset(BROAD_ETFS) | frozenset(MUTUAL_FUNDS)
