"""The broad fund universe downloaded by scripts/fetch_data.py besides the core lists in that script: the
most-held US-listed ETFs across asset classes and about 150 popular mutual funds (Yahoo serves mutual funds
as a daily NAV with dividends, i.e. a total-return history, most from the 1980s or their launch).

These are refreshed in rotating batches (BROAD_PER_RUN in scripts/fetch_data.py): each run downloads the
files that are missing first, then the ones updated longest ago, so every run stays short and polite to
Yahoo. A symbol Yahoo doesn't know is retried once a month, not every run.

They are funds, never index members: backtester/data.py strips every symbol here from the Nasdaq-100
membership history. To add a symbol, append it to the right list (or put it in data/extra_tickers.txt).
"""
from __future__ import annotations

# ETFs by asset class (the core list in scripts/fetch_data.py already has many; duplicates are harmless)
BROAD_ETFS_BY_CLASS = {
    "US total market / large cap": """
VTI VOO SPY IVV ITOT SCHB SPTM IWV VV SCHX IWB SPLG VONE MGC VXF DIA RSP OEF XLG SCHK ESGU ESGV SUSA DSI""",
    "US large growth / value": """
VUG VTV IWF IWD SCHG SCHV SPYG SPYV IVW IVE VONG VONV MGK MGV IUSG IUSV VOOG VOOV RPG RPV IWY IWX""",
    "US mid cap": """
VO IJH MDY IWR SCHM SPMD VOE VOT IWS IWP IJK IJJ XMLV XMHQ""",
    "US small cap": """
VB IJR IWM SCHA SPSM VBR VBK IWN IWO IJS IJT SLYV SLYG VTWO VIOO VIOV CALF IWC""",
    "Avantis": """
AVUV AVDV AVEM AVLV AVUS AVDE AVIV AVES AVSC AVMV AVRE AVIG AVSD""",
    "Dimensional": """
DFAC DFAU DFUS DFAT DFSV DFLV DFAS DFAI DFIV DFIS DISV DFEM DFEV DFAX DFCF DFIP DFNM DFSD DFAR DFGR""",
    "factor / smart beta": """
MTUM QUAL USMV VLUE SIZE SPHQ SPLV SPHB VFMF VFQY VFVA VFMO VFMV COWZ MOAT FNDX FNDA FNDF PRF JQUA
IMTM IQLT IVLU EFAV EEMV ACWV""",
    "dividend / income": """
SCHD VIG VYM DVY HDV SDY NOBL DGRO FDVV SPYD DGRW VYMI VIGI IDV JEPI JEPQ DIVO QYLD XYLD RYLD""",
    "growth / thematic": """
QQQ QQQM ONEQ ARKK ARKG ARKW ARKQ ARKF TAN ICLN LIT URA BOTZ ROBO HACK CIBR SKYY CLOU FINX ESPO BLOK KWEB
PBW FAN FDN IGV SOXX SMH XSD""",
    "sector (SPDR / Vanguard / iShares)": """
XLK XLF XLE XLV XLY XLP XLI XLU XLB XLRE XLC VGT VFH VDE VHT VCR VDC VIS VPU VAW VOX
IYW IYF IYE IYH IYC IYK IYJ IDU IYM IYZ IYT IBB IHI IHF ITA ITB IAK IAT KRE KBE XBI XHB XRT XME XOP XES
XAR XPH XHE XTN XSW OIH PAVE JETS IGF GRID""",
    "international broad / regional": """
VEA VXUS VEU VWO IEFA IEMG EFA EEM SCHF SCHE SCHC SPDW SPEM IXUS ACWI ACWX VT URTH EFG EFV SCZ VSS VGK VPL
IEUR EZU FEZ HEDJ DXJ GWX IDEV IEV ILF AAXJ EPP EWX""",
    "country": """
EWJ EWG EWU EWZ FXI MCHI INDA EWC EWA EWY EWT EWH EWS EWM EWP EWI EWQ EWL EWN EWD EWK EWO ENZL EDEN EFNL
ENOR EIRL EWW ECH EPOL TUR EZA EIDO THD EPHE VNM KSA ARGT GXC ASHR INDY SMIN EPI EWZS""",
    "US Treasuries / aggregate": """
AGG BND IUSB SCHZ SPAB FBND TOTL BSV BIV BLV VGSH VGIT VGLT GOVT SHY IEI IEF TLH TLT EDV ZROZ SPTS SPTI
SPTL SCHO SCHR SCHQ ISTB VMBS MBB SPMB""",
    "corporate bonds": """
VCSH VCIT VCLT IGSB IGIB IGLB USIG LQD SPSB SPIB SPLB SCHI SCHJ""",
    "high yield / loans": """
HYG JNK SHYG SJNK USHY HYLB ANGL FALN BKLN SRLN""",
    "international / EM bonds": """
BNDX IAGG BWX IGOV EMB VWOB PCY EMLC LEMB""",
    "municipal bonds": """
MUB VTEB TFI SUB SHM HYD HYMB PZA""",
    "TIPS": """
TIP SCHP VTIP STIP SPIP LTPZ TIPX TDTT""",
    "cash / ultra-short": """
BIL SGOV SHV TFLO USFR FLOT MINT JPST NEAR ICSH GSY VRIG FLRN""",
    "real estate": """
VNQ VNQI RWO REET RWR SCHH IYR USRT ICF RWX REM MORT FREL""",
    "commodities / precious metals": """
DBC PDBC GSG DJP BCI COMT CMDY FTGC USCI DBA DBB DBE DBO DBP GLD IAU GLDM SGOL BAR AAAU SLV SIVR PPLT PALL
USO BNO UNG UGA CPER CORN WEAT SOYB GDX GDXJ SIL""",
    "alternatives / managed futures": """
TAIL CTA DBMF KMLM BTAL QAI MNA RPAR NTSX NTSI NTSE PFIX SVOL""",
    "currencies": """
UUP UDN USDU FXE FXY FXF FXB FXA FXC""",
    "crypto": """
IBIT FBTC BITB ARKB GBTC ETHA ETHE BITO""",
}

# leveraged and inverse ETFs used in Composer-style symphonies (ProShares, Direxion, MicroSectors, ...)
LEVERAGED_ETFS = """
TQQQ SQQQ QLD QID PSQ UPRO SPXU SSO SDS SH SPXL SPXS SPUU UDOW SDOW DDM DXD DOG UWM TWM RWM URTY SRTY TNA TZA
MVV MZZ UMDD SMDD MIDU SAA SDD ROM REW USD SSG UYG SKF RXL RXD UGE SZK UXI UYM SMN DIG DUG URE SRS UPW SDP
BIB BIS UBT TBT TBF TBX UST PST TTT TMF TMV TYD TYO UCO SCO BOIL KOLD UGL GLL AGQ ZSL YCS YCL EUO ULE
SOXL SOXS TECL TECS FAS FAZ ERX ERY LABU LABD DRN DRV CURE DPST NAIL RETL DFEN WEBL WEBS HIBL HIBS UTSL
PILL TPOR WANT DUSL BRZU KORU MEXX EURL CHAU CWEB YINN YANG EDC EDZ INDL JNUG JDST NUGT DUST GUSH DRIP
FNGU FNGD FNGO BNKU BNKD NRGU NRGD OILU OILD GDXU GDXD
BITX BITI BITU SBIT ETHU ETHT ETHD CONL NVDL NVDS NVDX NVDQ TSLL TSLQ TSLS MSTU MSTZ AAPU AMZU GGLL MSFU METU
UVXY SVXY VIXY VIXM UVIX SVIX TARK SARK
"""

# popular mutual funds (Yahoo symbols); daily NAV with dividends
MUTUAL_FUNDS_BY_FAMILY = {
    "Vanguard": """
VFINX VFIAX VTSMX VTSAX VTIAX VGTSX VBMFX VBTLX VWELX VWENX VWINX VWIAX VGSLX VGSIX VFSTX VFSUX VWEHX VWEAX
VIPSX VAIPX VFITX VSIGX VUSTX VLGSX VBIRX VBILX VBLTX VWESX VWETX VFICX VWITX VWIUX VWLTX VWLUX VWSTX
VMLTX VTEAX VTABX VTMGX VEIEX VEMAX VEURX VPACX VTRIX VINEX VIMSX VIMAX NAESX VSMAX VISVX VSIAX VISGX
VSGAX VIVAX VVIAX VIGRX VIGAX VEXMX VEXAX VHDYX VDIGX VDADX VPMCX VPCCX VPMAX VWUSX VWNDX VWNFX VGHCX
VGENX VGPMX VTWSX VBIAX VBINX VASGX VASIX VSCGX VSMGX VGSTX VQNPX VHGEX VTMSX VMVIX VMGIX VFTSX VSEQX""",
    "Fidelity": """
FXAIX FSKAX FTIHX FXNAX FCNTX FMAGX FDGRX FBGRX FLPSX FOCPX FSELX FSPTX FBIOX FDVLX FEQIX FEQTX FGRIX
FPURX FBALX FFIDX FDIVX FIEUX FOSFX FSMDX FSSNX FSMAX FZROX FZILX FNILX FUAMX FGOVX FTBFX FNMIX FAGIX SPHIX
FRESX FSUTX FSENX FSCHX FSDAX FSRBX FSHCX FSCPX FSAGX FSRRX FSICX FLTMX""",
    "Dimensional": """
DFSVX DFLVX DFUSX DFQTX DFEOX DFCEX DFEMX DFEVX DFIVX DISVX DFISX DFALX DFSCX DFSTX DFREX DFGBX DFIHX
DFIEX DFVEX DFFVX DFIGX DFGEX""",
    "PIMCO": """
PTTRX PTTAX PIMIX PFORX PFUIX PCRIX PCRAX PRRIX PHIYX PEBIX PAAIX PAUIX PSTKX PSLDX PEDIX PGOVX PTSHX PTLDX""",
    "American Funds": """
AGTHX AIVSX ANCFX AWSHX AMCPX CWGIX AEPGX NEWFX SMCWX ANWPX CAIBX AMECX ABALX ABNDX AHITX""",
    "other": """
PRPFX VPMCX DODGX DODFX DODIX DODBX FAIRX SEQUX OAKMX OAKIX PRWCX PRGFX TRBCX PRNHX PRHSX PRDGX PRBLX
POAGX POGRX TWCUX BRUFX MERFX QSPIX AQMIX QMNIX SGIIX SGENX LSBRX MWTRX MWTIX HAINX HACAX MALOX TEPLX
FKINX ULPIX UOPIX RYNVX""",
}

# stocks outside the Nasdaq-100 that symphonies use (kept apart from the funds)
EXTRA_STOCKS = "SQM"


def _split(s: str) -> list[str]:
    return list(dict.fromkeys(s.split()))


BROAD_ETFS = _split(" ".join(BROAD_ETFS_BY_CLASS.values()) + " " + LEVERAGED_ETFS)
MUTUAL_FUNDS = _split(" ".join(MUTUAL_FUNDS_BY_FAMILY.values()))
BROAD_STOCKS = _split(EXTRA_STOCKS)
ALL_FUNDS = frozenset(BROAD_ETFS) | frozenset(MUTUAL_FUNDS)
