"""A library of classic, published strategies, written in the plain-English syntax."""

LIBRARY = [
    # --- asset allocation (Portfolio Visualizer / lazy portfolios)
    {"name": "60/40 stocks/bonds", "category": "Asset allocation", "text": "hold 60% SPY and 40% AGG, rebalance quarterly",
     "about": "The classic balanced portfolio."},
    {"name": "Permanent Portfolio", "category": "Asset allocation", "text": "equal weight SPY, TLT, GLD and BIL, rebalance yearly",
     "about": "Harry Browne: stocks, long bonds, gold and cash, 25% each."},
    {"name": "All Weather (simplified)", "category": "Asset allocation", "text": "hold 30% SPY, 40% TLT, 15% IEF, 7.5% GLD and 7.5% DBC, rebalance quarterly",
     "about": "Ray Dalio's risk-balanced mix."},
    {"name": "Golden Butterfly", "category": "Asset allocation", "text": "hold 20% VTI, 20% IWM, 20% TLT, 20% SHY and 20% GLD, rebalance yearly",
     "about": "Tyler's five-way split with a small-cap value tilt (IWM stands in)."},
    {"name": "Three-fund portfolio", "category": "Asset allocation", "text": "hold 50% VTI, 30% EFA and 20% BND, rebalance yearly",
     "about": "Bogleheads: US stocks, international stocks, bonds."},
    {"name": "Risk parity (inverse vol)", "category": "Asset allocation", "text": "inverse volatility weighted SPY, TLT, GLD and DBC using a 60 day lookback, rebalance monthly",
     "about": "Each asset contributes roughly equal volatility."},
    # --- tactical / momentum (Composer, PV tactical models)
    {"name": "Faber 10-month timing", "category": "Tactical", "text": "hold SPY when it is above its 10-month moving average, otherwise cash, rebalance monthly",
     "about": "Meb Faber (2007): be in stocks only above the 10-month average."},
    {"name": "GTAA 5 (Faber)", "category": "Tactical", "text": "equal weight SPY, EFA, AGG, VNQ and DBC, rebalance monthly",
     "about": "The ivy-style five-asset base; add timing with the block editor."},
    {"name": "Dual momentum (Antonacci)", "category": "Tactical", "text": "dual momentum between SPY and EFA with AGG as the safe asset",
     "about": "Relative momentum between US and international stocks, absolute momentum vs T-bills."},
    {"name": "Sector rotation", "category": "Tactical", "text": "hold the top 3 sector ETFs by 6 month momentum, rebalance monthly",
     "about": "Own the three strongest S&P sectors."},
    {"name": "Nasdaq-100 momentum (point-in-time)", "category": "Tactical", "text": "hold the top 10 Nasdaq 100 stocks by 12 month return, rebalance monthly, since 2005",
     "about": "Cross-sectional momentum inside the index, using historical membership."},
    {"name": "Low-volatility Nasdaq-100", "category": "Tactical", "text": "hold the bottom 10 Nasdaq 100 stocks by 60 day volatility, rebalance monthly, since 2005",
     "about": "The low-volatility anomaly within the index."},
    {"name": "QQQ/TLT regime switch", "category": "Tactical", "text": "if SPY is above its 200-day moving average hold QQQ, otherwise hold TLT, rebalance daily",
     "about": "Growth when the trend is up, long bonds when it isn't."},
    {"name": "Leveraged trend (TQQQ)", "category": "Tactical", "text": "if QQQ is above its 200 day moving average hold TQQQ, otherwise hold BIL, rebalance daily",
     "about": "Only hold 3x Nasdaq in an uptrend."},
    # --- short-term signals (TradingView / QuantConnect style)
    {"name": "RSI(2) mean reversion (Connors)", "category": "Mean reversion", "text": "buy SPY at the close when RSI(2) is below 10 and it is above its 200-day moving average, sell when it closes above its 5-day moving average",
     "about": "Larry Connors' short-term pullback in an uptrend."},
    {"name": "RSI(2) across the Nasdaq-100", "category": "Mean reversion", "text": "buy Nasdaq 100 stocks at the close when RSI(2) is below 5 and it is above its 200-day moving average, sell when it closes above its 5-day moving average, max 10 positions, since 2005",
     "about": "The same idea on every index member, 10 slots."},
    {"name": "IBS reversion", "category": "Mean reversion", "text": "buy QQQ at the close when it closes in the bottom 20% of its range, hold 1 day",
     "about": "Internal bar strength: weak closes tend to bounce."},
    {"name": "Down 3 days in a row", "category": "Mean reversion", "text": "buy QQQ at the close when it is down 3 days in a row, hold 3 days",
     "about": "Buy short-term exhaustion."},
    {"name": "Turn of the month", "category": "Calendar", "text": "buy SPY at the close on the last trading day of the month, sell at the close 4 days later",
     "about": "Returns cluster around month-end flows."},
    {"name": "Donchian breakout with ATR stop", "category": "Trend following", "text": "buy QQQ when it closes above its 55 day high, with a 2 ATR stop and a 3 ATR trailing stop",
     "about": "Turtle-style breakout with volatility stops."},
    {"name": "Golden cross", "category": "Trend following", "text": "buy SPY when the 50 day moving average crosses above the 200 day moving average, sell when the 50 day moving average crosses below the 200 day moving average",
     "about": "The classic crossover."},
    {"name": "MACD crossover", "category": "Trend following", "text": "buy QQQ when MACD crosses above its signal line, sell when MACD crosses below its signal line",
     "about": "12/26/9 MACD signals."},
    {"name": "Buy the VIX spike", "category": "Volatility", "text": "buy SPY when VIX is above 30, hold 20 days",
     "about": "Fear spikes have historically been buying opportunities."},
    {"name": "Monthly dollar-cost averaging", "category": "Savings plan", "text": "buy and hold SPY, add $500 every month",
     "about": "Regular contributions; see money-weighted vs time-weighted return."},
    {"name": "4% rule retirement", "category": "Retirement", "text": "hold 60% SPY and 40% AGG, withdraw 4% per year adjusted for inflation, starting with $1,000,000, rebalance annually",
     "about": "Bengen's safe-withdrawal test, with a Monte Carlo success rate."},
]
